// client-react/src/components/title-banner/TitleBanner.tsx
import './TitleBanner.css';
import picture from '../../assets/libled.jpg';

const TitleBanner = ({ title = "" }) => {
    return (
        <div className="banner-header">
            <div className="title">{title}</div>
            <div className="image">
                <img src={picture} alt="banner" />
            </div>
        </div>
    );
};

export default TitleBanner;

// client/src/app/components/title-banner/title-banner.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-title-banner',
  standalone: true,
  imports: [],
  templateUrl: './title-banner.component.html',
  styleUrl: './title-banner.component.scss',
})
export class TitleBannerComponent {
  @Input() title: string = '';
}

<div class="header">
  <div class="title">{{ title }}</div>
  <div class="image">
    <img src="../../../assets/libled.jpg" />
  </div>
</div>
