// client-react/src/components/event-add/EventAdd.tsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import TitleBanner from '../title-banner/TitleBanner';
import EventService from '../../services/EventService';

const EventAdd = () => {
    const [event, setEvent] = useState({
        name: "",
        dateTime: new Date().toISOString(),
        location: "",
        description: "",
    });

    const navigate = useNavigate();

    const onSubmit = (e: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
        e.preventDefault();

        if (event.dateTime) setEvent({ ...event, dateTime: new Date(event.dateTime).toISOString() });

        EventService.post(event).then(() => {
            navigate('/');
        });
    };

    return (
        <div className="form-page-container">
            <TitleBanner title="Add Event" />
            <div className="form-container">
                <div className="title">Add Event</div>
                <div className="form">
                    <div className="form-group">
                        <label htmlFor="name">Event Name:</label>
                        <input type="text" id="name" value={event.name} onChange={e => setEvent({ ...event, name: e.target.value })} />
                    </div>
                    <div className="form-group">
                        <label htmlFor="date">Time & date:</label>
                        <input type="datetime-local" id="date" value={event.dateTime} onChange={e => setEvent({ ...event, dateTime: e.target.value })} />
                    </div>
                    <div className="form-group">
                        <label htmlFor="location">Location:</label>
                        <input type="text" id="location" value={event.location} onChange={e => setEvent({ ...event, location: e.target.value })} />
                    </div>
                    <div className="form-group">
                        <label htmlFor="description">Description:</label>
                        <textarea className="input" id="description" value={event.description} onChange={e => setEvent({ ...event, description: e.target.value })}></textarea>
                    </div>
                </div>
                <div className="buttons">
                    <button className="button secondary" onClick={() => navigate('/')}>Back</button>
                    <button className="button primary" onClick={(e) => onSubmit(e)}>Add</button>
                </div>
            </div>
        </div>
    );
};

export default EventAdd;

// client/src/app/components/event-add/event-add.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { IEvent } from '../../models/IEvent';
import { EventService } from '../../services/event.service';
import { Router, RouterModule } from '@angular/router';
import { TitleBannerComponent } from '../title-banner/title-banner.component';
import { CustomDatetimePipe } from '../../pipes/custom-datetime.pipe';
import { tap } from 'rxjs';

@Component({
  selector: 'app-add-event',
  standalone: true,
  imports: [
    FormsModule,
    RouterModule,
    TitleBannerComponent,
    CustomDatetimePipe,
  ],
  templateUrl: './event-add.component.html',
  styleUrl: './event-add.component.scss',
})
export class EventAddComponent {
  event: IEvent = {
    name: '',
    dateTime: new Date().toUTCString(),
    location: '',
    description: '',
  };

  constructor(private eventService: EventService, private router: Router) {}

  onSubmit(): void {
    if (this.event.dateTime) {
      this.event.dateTime = new Date(this.event.dateTime).toISOString();
    }

    this.eventService
      .post(this.event)
      .pipe(
        tap((response: any) => {
          if (response.id) this.router.navigate(['/']);
        })
      )
      .subscribe();
  }
}

<div class="form-page-container">
  <app-title-banner [title]="'Ürituse lisamine'"></app-title-banner>

  <div class="form-container">
    <div class="title">Ürituse lisamine</div>

    <div class="form">
      <div class="form-group">
        <label for="name">Ürituse nimi:</label>
        <input type="text" id="name" [(ngModel)]="event.name" />
      </div>

      <div class="form-group">
        <label for="date">Toimumisaeg:</label>
        <input type="datetime-local" id="date" [(ngModel)]="event.dateTime" />
      </div>

      <div class="form-group">
        <label for="location">Koht:</label>
        <input type="text" id="location" [(ngModel)]="event.location" />
      </div>

      <div class="form-group">
        <label for="description">Lisa info:</label>
        <textarea
          class="input"
          id="description"
          [(ngModel)]="event.description"
        ></textarea>
      </div>
    </div>

    <div class="buttons">
      <button class="button secondary" [routerLink]="'/'">Tagasi</button>
      <button class="button primary" (click)="onSubmit()">Lisa</button>
    </div>
  </div>
</div>
