// client-react/src/components/footer/Footer.tsx
import React from 'react';
import { Link } from 'react-router-dom';
import './Footer.css';

const infoByColumn = [
    {
        htmlColumnLabel: 'Curabitur',
        items: [
            { htmlLabel: 'Emauris', linkPath: '/emauris' },
            { htmlLabel: 'Khringilla', linkPath: '/khringilla' },
            { htmlLabel: 'Oin magna sem', linkPath: '/oin-magna-sem' },
            { htmlLabel: 'Sed consequat', linkPath: '/sed-consequat' },
        ],
    },
    {
        htmlColumnLabel: 'Fusce',
        items: [
            { htmlLabel: 'Emauris', linkPath: '/emauris' },
            { htmlLabel: 'Khringilla', linkPath: '/khringilla' },
            { htmlLabel: 'Oin magna sem', linkPath: '/oin-magna-sem' },
            { htmlLabel: 'Sed consequat', linkPath: '/sed-consequat' },
        ],
    },
    {
        htmlColumnLabel: 'Contact',
        items: [
            { htmlLabel: '<b>Office: Tallinas</b>' },
            { htmlLabel: 'Väike-Aasia 1, 22415 Tallinn' },
            { htmlLabel: 'Telefon: 691 1234' },
            { htmlLabel: 'Faks: 605 5678' },
        ],
    },
    {
        htmlColumnLabel: '&nbsp;',
        items: [
            { htmlLabel: '<b>Other office</b>' },
            { htmlLabel: 'Oja tn 7' },
            { htmlLabel: 'Telefon: 60512345' },
            { htmlLabel: 'FaksÖ 6050987' },
        ],
    },
] as { htmlColumnLabel?: string; items: { htmlLabel: string; linkPath?: string }[] }[];

const Footer = () => {
    return (
        <div className="footer">
            {infoByColumn.map((column, index) => (
                <div key={index} className="column">
                    <div className="column-title" dangerouslySetInnerHTML={{ __html: column.htmlColumnLabel || '' }} />
                    {column.items.map((item, i) => (
                        item.linkPath ?
                            <a key={i} href={item.linkPath} className="column-link" dangerouslySetInnerHTML={{ __html: item.htmlLabel }} /> :
                            <div key={i} dangerouslySetInnerHTML={{ __html: item.htmlLabel }} />
                    ))}
                </div>
            ))}
        </div>
    );
};

export default Footer;

// client/src/app/components/footer/footer.component.ts
import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.scss',
})
export class FooterComponent {
  infoByColumn: {
    htmlColumnLabel?: string;
    items: { htmlLabel: string; linkPath?: string }[];
  }[] = [
    {
      htmlColumnLabel: 'Curabitur',
      items: [
        { htmlLabel: 'Emauris', linkPath: '/emauris' },
        { htmlLabel: 'Khringilla', linkPath: '/khringilla' },
        { htmlLabel: 'Oin magna sem', linkPath: '/oin-magna-sem' },
        { htmlLabel: 'Sed consequat', linkPath: '/sed-consequat' },
      ],
    },
    {
      htmlColumnLabel: 'Fusce',
      items: [
        { htmlLabel: 'Emauris', linkPath: '/emauris' },
        { htmlLabel: 'Khringilla', linkPath: '/khringilla' },
        { htmlLabel: 'Oin magna sem', linkPath: '/oin-magna-sem' },
        { htmlLabel: 'Sed consequat', linkPath: '/sed-consequat' },
      ],
    },
    {
      htmlColumnLabel: 'Kontakt',
      items: [
        { htmlLabel: '<b>Peakontor: Tallinas</b>' },
        { htmlLabel: 'Väike-Ameerika 1, 11415 Tallinn' },
        { htmlLabel: 'Telefon: 605 4450' },
        { htmlLabel: 'Faks: 605 3186' },
      ],
    },
    {
      htmlColumnLabel: '&nbsp;',
      items: [
        { htmlLabel: '<b>Harjukontor: Võrus</b>' },
        { htmlLabel: 'Oja tn 7 (Külastusaadress)' },
        { htmlLabel: 'Telefon: 6053330' },
        { htmlLabel: 'FaksÖ 6053155' },
      ],
    },
  ];
}

<div class="footer">
  <div *ngFor="let column of infoByColumn" class="column">
    <div class="column-title" [innerHTML]="column.htmlColumnLabel"></div>
    <ng-container *ngFor="let item of column.items">
      <a
        *ngIf="item.linkPath"
        class="column-link"
        [routerLink]="item.linkPath"
        [innerHTML]="item.htmlLabel"
      ></a>
      <div *ngIf="!item.linkPath" [innerHTML]="item.htmlLabel"></div>
    </ng-container>
  </div>
</div>
