// client/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { EventService } from '../../services/event.service';
import { IEvent } from '../../models/IEvent';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss',
})
export class HomeComponent implements OnInit {
  futureEvents: IEvent[] = [];
  pastEvents: IEvent[] = [];
  homeHtmlText =
    'Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium <b>doloremque laudantium</b>, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non';

  constructor(private eventService: EventService) {}

  ngOnInit(): void {
    this.loadEvents();
  }

  loadEvents(): void {
    const search = {
      sortField: 'updatedAt',
    };

    this.eventService.getAll(search).subscribe((events) => {
      this.futureEvents = events?.filter(
        (e) => new Date(e.dateTime) > new Date()
      );

      this.pastEvents = events?.filter(
        (e) => new Date(e.dateTime) < new Date()
      );
    });
  }

  removeEvent(id?: string): void {
    if (!id) return;

    this.eventService.delete(id).subscribe(() => {
      this.loadEvents();
    });
  }
}

<div class="home-container">
  <div class="banner">
    <div class="banner-text">
      <span [innerHTML]="homeHtmlText"></span>
    </div>
    <img class="banner-image" src="../../../assets/pilt.jpg" alt="banner" />
  </div>

  <div class="event-lists">
    <div class="event-list">
      <div class="header">Tulevased üritused</div>
      <div class="event-list-body">
        <table>
          <div *ngIf="!futureEvents?.length">Üritusi pole</div>
          <tr *ngFor="let event of futureEvents; index as i">
            <td>{{ i + 1 }}</td>
            <td>{{ event.name }}</td>
            <td>{{ event.dateTime | date }}</td>
            <td>
              <a [routerLink]="['yritused', event.id]">OSALEJAD</a>
            </td>
            <td>
              <img
                class="remove-button"
                src="../../../assets/remove.svg"
                alt="remove"
                (click)="removeEvent(event.id)"
              />
            </td>
          </tr>
        </table>
        <a class="add-event" [routerLink]="'/lisa-yritus'">LISA ÜRITUS</a>
      </div>
    </div>
    <div class="event-list">
      <div class="header">Toimunud üritused</div>
      <div class="event-list-body">
        <div *ngIf="!pastEvents?.length">Üritusi pole</div>
        <table>
          <tr *ngFor="let event of pastEvents; index as i">
            <td>{{ i + 1 }}</td>
            <td>{{ event.name }}</td>
            <td>{{ event.dateTime | date }}</td>
            <td>OSALEJAD</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
</div>

// client-react/src/components/home/Home.tsx
import React, { useState, useEffect } from 'react';
import EventService from '../../services/EventService';
import './Home.css';
import { Link } from 'react-router-dom';
import { IEvent } from '../../models/IEvent';
import bannerImage from '../../assets/pilt.jpg';
import removeIcon from '../../assets/remove.svg';

const Home = () => {
    const [futureEvents, setFutureEvents] = useState<IEvent[]>([]);
    const [pastEvents, setPastEvents] = useState<IEvent[]>([]);

    const homeHtmlText =
        "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium <b>doloremque laudantium</b>, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non";

    useEffect(() => {
        loadEvents();
    }, []);

    const loadEvents = () => {
        const search = {
            sortField: "updatedAt",
        };

        EventService.getAll(search).then(response => {
            const events = response.data;

            setFutureEvents(events.filter(e => new Date(e.dateTime) > new Date()));
            setPastEvents(events.filter(e => new Date(e.dateTime) < new Date()));
        });
    };

    const removeEvent = (id: string) => {
        if (!id) return;

        EventService.remove(id).then(() => {
            loadEvents();
        });
    };

    return (
        <div className="home-container">
            <div className="home-banner">
                <div className="banner-text">
                    <span dangerouslySetInnerHTML={{ __html: homeHtmlText }}></span>
                </div>
                <img className="banner-image" src={bannerImage} alt="banner" />
            </div>
            <div className="event-lists">
                <div className="event-list">
                    <div className="event-list-header">Future Events</div>
                    <div className="event-list-body">
                        {!futureEvents.length && <div>No events</div>}
                        <table>
                            <tbody>
                                {futureEvents.map((event, i) => (
                                    <tr key={i}>
                                        <td>{i + 1}</td>
                                        <td>{event.name}</td>
                                        <td>{new Date(event.dateTime).toLocaleDateString()}</td>
                                        <td>
                                            <Link to={`/events/${event.id}`}>PARTICIPANTS</Link>
                                        </td>
                                        <td>
                                            <img
                                                className="remove-button"
                                                src={removeIcon}
                                                alt="remove"
                                                onClick={() => removeEvent(event.id!)}
                                            />
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                        <Link className="add-event" to="/add-event">ADD EVENT</Link>
                    </div>
                </div>

                <div className="event-list">
                    <div className="event-list-header">Past Events</div>
                    <div className="event-list-body">
                        {!pastEvents.length && <div>No events</div>}
                        <table>
                            <tbody>
                                {pastEvents.map((event, i) => (
                                    <tr key={i}>
                                        <td>{i + 1}</td>
                                        <td>{event.name}</td>
                                        <td>{new Date(event.dateTime).toLocaleDateString()}</td>
                                        <td>PARTICIPANTS</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Home;
