// client/src/app/components/event-details/event-details.component.ts
import { Component, OnInit } from '@angular/core';
import { PersonService } from '../../services/person.service';
import { OrganizationService } from '../../services/organization.service';
import { IOrganization } from '../../models/IOrganization';
import { IEvent } from '../../models/IEvent';
import { EventService } from '../../services/event.service';
import { Router, RouterModule } from '@angular/router';
import { IPerson } from '../../models/IPerson';
import { TitleBannerComponent } from '../title-banner/title-banner.component';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { PaymentMethodService } from '../../services/payment-method.service';
import { IPaymentMethod } from '../../models/IPaymentMethod';
import { tap } from 'rxjs';

export type Participant = {
  id?: string;
  isOrganization: boolean;
  firstName: string;
  lastName: string;
  personalCode: string;
  numberOfParticipants: number;
  description: string;
  paymentMethodId: string;
  eventId?: string;
};

type ListParticipant = {
  id: string;
  name: string;
  code: string;
  updatedAt: Date;
  isOrganization: boolean;
};

@Component({
  selector: 'app-event-details',
  standalone: true,
  imports: [CommonModule, TitleBannerComponent, FormsModule, RouterModule],
  templateUrl: './event-details.component.html',
  styleUrl: './event-details.component.scss',
})
export class AddParticipantComponent implements OnInit {
  eventId?: string;
  event?: IEvent;
  eventParticipants: ListParticipant[] = [];

  paymentMethods: IPaymentMethod[] = [];

  newParticipant: Participant = {
    isOrganization: false,
    firstName: '',
    lastName: '',
    personalCode: '',
    paymentMethodId: '',
    numberOfParticipants: 0,
    description: '',
  };

  constructor(
    private router: Router,
    private eventService: EventService,
    private personService: PersonService,
    private organizationService: OrganizationService,
    private paymentMethodService: PaymentMethodService
  ) {}

  ngOnInit(): void {
    this.eventId = this.router.url.split('/')[2];

    this.eventService.get(this.eventId).subscribe((event) => {
      this.event = event;

      this.eventParticipants = [
        ...(event.people?.map((person) => ({
          id: person.id!,
          name: person.firstName + ' ' + person.lastName,
          code: person.personalCode,
          updatedAt: person.updatedAt!,
          isOrganization: false,
        })) || []),
        ...(event.organizations?.map((organization) => ({
          id: organization.id!,
          name: organization.name,
          code: organization.registrationNumber,
          updatedAt: organization.updatedAt!,
          isOrganization: true,
        })) || []),
      ];
    });

    this.paymentMethodService.getAll().subscribe((paymentMethods) => {
      this.paymentMethods = paymentMethods;

      if (paymentMethods[0].id)
        this.newParticipant.paymentMethodId = paymentMethods[0].id;
    });
  }

  onSubmit(): void {
    if (!this.eventId) return;

    this.newParticipant.isOrganization
      ? this.createOrganization()
      : this.createPerson();
  }

  removeParticipant(id?: string): void {
    if (!id) return;

    if (this.eventParticipants.find((p) => p.id === id)?.isOrganization) {
      this.organizationService.delete(id).subscribe(() => {
        this.eventParticipants = this.eventParticipants.filter(
          (p) => p.id !== id
        );
      });

      return;
    }

    this.personService.delete(id).subscribe(() => {
      this.eventParticipants = this.eventParticipants.filter(
        (p) => p.id !== id
      );
    });
  }

  switchParticipantType(): void {
    this.newParticipant.isOrganization = !this.newParticipant.isOrganization;
  }

  private createPerson() {
    const person: IPerson = {
      firstName: this.newParticipant.firstName,
      lastName: this.newParticipant.lastName,
      personalCode: this.newParticipant.personalCode,
      eventId: this.eventId!,
      paymentMethodId: this.newParticipant.paymentMethodId,
      description: this.newParticipant.description,
    };

    this.personService
      .post(person)
      .pipe(
        tap((response: any) => {
          if (response.id) {
            this.eventParticipants.push({
              id: response.id,
              name: person.firstName + ' ' + person.lastName,
              code: person.personalCode,
              updatedAt: person.updatedAt || new Date(),
              isOrganization: false,
            });
          }
        })
      )
      .subscribe();
  }

  private createOrganization() {
    const organization: IOrganization = {
      name: this.newParticipant.firstName + ' ' + this.newParticipant.lastName,
      description: this.newParticipant.description,
      registrationNumber: this.newParticipant.personalCode,
      numberOfParticipants: this.newParticipant.numberOfParticipants,
      eventId: this.eventId!,
      paymentMethodId: this.newParticipant.paymentMethodId,
    };

    this.organizationService
      .post(organization)
      .pipe(
        tap((response: any) => {
          if (response.id) {
            this.eventParticipants.push({
              id: response.id,
              name: organization.name,
              code: organization.registrationNumber,
              updatedAt: organization.updatedAt || new Date(),
              isOrganization: true,
            });
          }
        })
      )
      .subscribe();
  }
}

<div class="form-page-container">
  <app-title-banner [title]="'Osavõtjad'"></app-title-banner>

  <div class="form-container">
    <div class="title">Osavõtjad</div>

    <div class="form">
      <div class="form-group">
        <span class="label">Ürituse nimi:</span>
        <span class="input">{{ event?.name }}</span>
      </div>
      <div class="form-group">
        <span class="label">Toimumisaeg:</span>
        <span>{{ event?.dateTime | date }}</span>
      </div>
      <div class="form-group">
        <span class="label">Koht:</span>
        <span>{{ event?.location }}</span>
      </div>
      <div class="form-group">
        <div class="label"></div>
        <table class="participants-table">
          <tr *ngFor="let participant of eventParticipants; index as i">
            <td>{{ i + 1 }}</td>
            <td>{{ participant.name }}</td>
            <td>{{ participant.code }}</td>
            <td>
              <a
                [routerLink]="['/osalejad', participant.id]"
                [queryParams]="
                  participant.isOrganization ? { isOrganization: true } : {}
                "
                >VAATA</a
              >
            </td>
            <td
              class="remove-button"
              (click)="removeParticipant(participant.id)"
            >
              KUSTUTA
            </td>
          </tr>
        </table>
      </div>
    </div>

    <div class="title">Osavõtjate lisamine</div>

    <div class="form">
      <div class="participant-radio">
        <span>
          <input
            type="radio"
            id="individual"
            name="participantType"
            [checked]="!newParticipant.isOrganization"
            (change)="switchParticipantType()"
          />
          <label for="individual">Eraisik</label>
        </span>
        <span>
          <input
            type="radio"
            id="company"
            name="participantType"
            [checked]="newParticipant.isOrganization"
            (change)="switchParticipantType()"
          />
          <label for="company">Ettevõte</label>
        </span>
      </div>

      <div class="form-group">
        <label for="name"
          >{{ newParticipant.isOrganization ? "Nimi" : "Eesnimi" }}:</label
        >
        <input type="text" id="name" [(ngModel)]="newParticipant.firstName" />
      </div>

      <div class="form-group" *ngIf="!newParticipant.isOrganization">
        <label for="last-name">Perenimi:</label>
        <input
          type="text"
          id="last-name"
          [(ngModel)]="newParticipant.lastName"
        />
      </div>

      <div class="form-group">
        <label for="code"
          >{{ newParticipant.isOrganization ? "Reg nr" : "Isikukood" }}:</label
        >
        <input
          type="text"
          id="code"
          [(ngModel)]="newParticipant.personalCode"
        />
      </div>

      <div class="form-group" *ngIf="newParticipant.isOrganization">
        <label for="numberOfParticipants">Tulevate osavõtjate arv:</label>
        <input
          type="number"
          id="numberOfParticipants"
          [(ngModel)]="newParticipant.numberOfParticipants"
        />
      </div>

      <div class="form-group">
        <label for="paymentMethod">Makseviis:</label>
        <select
          id="paymentMethod"
          class="input"
          [(ngModel)]="newParticipant.paymentMethodId"
        >
          <option
            *ngFor="let paymentMethod of paymentMethods"
            value="{{ paymentMethod.id }}"
          >
            {{ paymentMethod.name }}
          </option>
        </select>
      </div>

      <div class="form-group">
        <label for="description">Lisainfo:</label>
        <textarea
          id="description"
          class="input"
          [(ngModel)]="newParticipant.description"
        ></textarea>
      </div>
    </div>

    <div class="buttons">
      <button class="button secondary" [routerLink]="'/'">Tagasi</button>
      <button class="button primary" (click)="onSubmit()">Salvesta</button>
    </div>
  </div>
</div>

// client-react/src/components/event-details/EventDetails.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate, NavigateOptions } from 'react-router-dom';
import EventService from '../../services/EventService';
import PersonService from '../../services/PersonService';
import OrganizationService from '../../services/OrganizationService';
import PaymentMethodService from '../../services/PaymentMethodService';
import { IListParticipant } from '../../models/IListParticipant';
import { IEvent } from '../../models/IEvent';
import { IPaymentMethod } from '../../models/IPaymentMethod';
import { IParticipant } from '../../models/IParticipant';
import { IOrganization } from '../../models/IOrganization';
import { IPerson } from '../../models/IPerson';
import TitleBanner from '../title-banner/TitleBanner';
import './EventDetails.css';

const EventDetails = () => {
    const { id: eventId } = useParams();
    const navigate = useNavigate();

    const [event, setEvent] = useState<IEvent | null>(null);
    const [eventParticipants, setEventParticipants] = useState<IListParticipant[]>([]);
    const [paymentMethods, setPaymentMethods] = useState<IPaymentMethod[]>([]);
    const [newParticipant, setNewParticipant] = useState<IParticipant>({
        isOrganization: false,
        firstName: "",
        lastName: "",
        personalCode: "",
        paymentMethodId: "",
        numberOfParticipants: 0,
        description: "",
    });

    useEffect(() => {
        EventService.get(eventId!).then((event) => {
            setEvent(event.data);
            setEventParticipants([
                ...(event.data.people?.map((person: IPerson): IListParticipant => ({
                    id: person.id,
                    name: person.firstName + " " + person.lastName,
                    code: person.personalCode,
                    updatedAt: person.updatedAt,
                    isOrganization: false,
                })) || []),
                ...(event.data.organizations?.map((organization: IOrganization): IListParticipant => ({
                    id: organization.id,
                    name: organization.name,
                    code: organization.registrationNumber,
                    updatedAt: organization.updatedAt,
                    isOrganization: true,
                })) || []),
            ]);
        });

        PaymentMethodService.getAll().then((response) => {
            const paymentMethods = response.data;
            setPaymentMethods(paymentMethods);
            if (paymentMethods[0].id) {
                setNewParticipant(prev => ({ ...prev, paymentMethodId: paymentMethods[0].id! }));
            }
        });
    }, [eventId]);

    const onSubmit = () => {
        if (!eventId) return;

        newParticipant.isOrganization
            ? createOrganization()
            : createPerson();
    };

    const removeParticipant = (id: string) => {
        if (!id) return;

        if (eventParticipants.find((p) => p.id === id)?.isOrganization) {
            OrganizationService.remove(id).then(() => {
                setEventParticipants(prev => prev.filter((p) => p.id !== id));
            });
            return;
        }

        PersonService.remove(id).then(() => {
            setEventParticipants(prev => prev.filter((p) => p.id !== id));
        });
    };

    const switchParticipantType = () => {
        setNewParticipant(prev => ({ ...prev, isOrganization: !prev.isOrganization }));
    };

    const createPerson = () => {
        const person: IPerson = {
            firstName: newParticipant.firstName,
            lastName: newParticipant.lastName,
            personalCode: newParticipant.personalCode,
            eventId: eventId!,
            paymentMethodId: newParticipant.paymentMethodId,
            description: newParticipant.description,
        };

        PersonService.post(person).then((response) => {
            if (response.data.id) {
                setEventParticipants(prev => [...prev, {
                    id: response.data.id,
                    name: person.firstName + " " + person.lastName,
                    code: person.personalCode,
                    updatedAt: person.updatedAt || new Date(),
                    isOrganization: false,
                }]);
            }
        });
    };

    const createOrganization = () => {
        const organization = {
            name: newParticipant.firstName + " " + newParticipant.lastName,
            description: newParticipant.description,
            registrationNumber: newParticipant.personalCode,
            numberOfParticipants: newParticipant.numberOfParticipants,
            eventId,
            paymentMethodId: newParticipant.paymentMethodId,
        } as IOrganization;

        OrganizationService.post(organization).then((response) => {
            if (response.data.id) {
                setEventParticipants(prev => [...prev, {
                    id: response.data.id,
                    name: organization.name,
                    code: organization.registrationNumber,
                    eventId: organization.eventId!,
                    updatedAt: organization.updatedAt || new Date(),
                    isOrganization: true,
                } as IListParticipant]);
            }
        });
    };

    return (
        <div className="form-page-container">
            <TitleBanner title="Participants" />

            <div className="form-container">
                <div className="title">Participants</div>

                <div className="form">
                    <div className="form-group">
                        <span className="label">Event Name:</span>
                        <span className="input">{event?.name}</span>
                    </div>
                    <div className="form-group">
                        <span className="label">Date:</span>
                        <span>{new Date(event?.dateTime ?? "").toLocaleDateString()}</span>
                    </div>
                    <div className="form-group">
                        <span className="label">Location:</span>
                        <span>{event?.location}</span>
                    </div>
                    <div className="form-group">
                        <div className="label"></div>
                        <table className="participants-table">
                            {eventParticipants.map((participant, i) => (
                                <tr key={participant.id}>
                                    <td>{i + 1}</td>
                                    <td>{participant.name}</td>
                                    <td>{participant.code}</td>
                                    <td>
                                        <a
                                            href={`/participants/${participant.id}`}
                                            onClick={(e) => {
                                                e.preventDefault();
                                                navigate(`/participants/${participant.id}`, {
                                                    isOrganization: participant.isOrganization,
                                                } as NavigateOptions);
                                            }}
                                        >
                                            VIEW
                                        </a>
                                    </td>
                                    <td
                                        className="remove-button"
                                        onClick={() => removeParticipant(participant.id!)}
                                    >
                                        REMOVE
                                    </td>
                                </tr>
                            ))}
                        </table>
                    </div>
                </div>

                <div className="title">Add Participants</div>

                <div className="form">
                    <div className="participant-radio">
                        <span>
                            <input
                                type="radio"
                                id="individual"
                                name="participantType"
                                checked={!newParticipant.isOrganization}
                                onChange={switchParticipantType}
                            />
                            <label htmlFor="individual">Person</label>
                        </span>
                        <span>
                            <input
                                type="radio"
                                id="company"
                                name="participantType"
                                checked={newParticipant.isOrganization}
                                onChange={switchParticipantType}
                            />
                            <label htmlFor="company">Organization</label>
                        </span>
                    </div>
                    <div className="form-group">
                        <label htmlFor="name">
                            {newParticipant.isOrganization ? "Name" : "First Name"}:
                        </label>
                        <input
                            type="text"
                            id="name"
                            value={newParticipant.firstName}
                            onChange={(e) =>
                                setNewParticipant((prev) => ({
                                    ...prev,
                                    firstName: e.target.value,
                                }))
                            }
                        />
                    </div>

                    {!newParticipant.isOrganization && (
                        <div className="form-group">
                            <label htmlFor="last-name">Last Name:</label>
                            <input
                                type="text"
                                id="last-name"
                                value={newParticipant.lastName}
                                onChange={(e) =>
                                    setNewParticipant((prev) => ({
                                        ...prev,
                                        lastName: e.target.value,
                                    }))
                                }
                            />
                        </div>
                    )}

                    <div className="form-group">
                        <label htmlFor="code">
                            {newParticipant.isOrganization ? "Reg nr" : "Personal Code"}:
                        </label>
                        <input
                            type="text"
                            id="code"
                            value={newParticipant.personalCode}
                            onChange={(e) =>
                                setNewParticipant((prev) => ({
                                    ...prev,
                                    personalCode: e.target.value,
                                }))
                            }
                        />
                    </div>

                    {newParticipant.isOrganization && (
                        <div className="form-group">
                            <label htmlFor="numberOfParticipants">Event participants:</label>
                            <input
                                type="number"
                                id="numberOfParticipants"
                                value={newParticipant.numberOfParticipants}
                                onChange={(e) =>
                                    setNewParticipant((prev) => ({
                                        ...prev,
                                        numberOfParticipants: parseInt(e.target.value),
                                    }))
                                }
                            />
                        </div>
                    )}

                    <div className="form-group">
                        <label htmlFor="paymentMethod">Payment by:</label>
                        <select
                            id="paymentMethod"
                            className="input"
                            value={newParticipant.paymentMethodId}
                            onChange={(e) =>
                                setNewParticipant((prev) => ({
                                    ...prev,
                                    paymentMethodId: e.target.value,
                                }))
                            }
                        >
                            {paymentMethods.map((paymentMethod) => (
                                <option key={paymentMethod.id} value={paymentMethod.id}>
                                    {paymentMethod.name}
                                </option>
                            ))}
                        </select>
                    </div>

                    <div className="form-group">
                        <label htmlFor="description">Description:</label>
                        <textarea
                            id="description"
                            className="input"
                            value={newParticipant.description}
                            onChange={(e) =>
                                setNewParticipant((prev) => ({
                                    ...prev,
                                    description: e.target.value,
                                }))
                            }
                        ></textarea>
                    </div>
                </div>

                <div className="buttons">
                    <button className="button secondary" onClick={() => navigate("/")}>
                        Back
                    </button>
                    <button className="button primary" onClick={onSubmit}>
                        Save
                    </button>
                </div>
            </div>
        </div>
    );
};

export default EventDetails;
