// client/src/app/components/participant-details/participant-details.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { OrganizationService } from '../../services/organization.service';
import { PaymentMethodService } from '../../services/payment-method.service';
import { PersonService } from '../../services/person.service';
import { Participant } from '../event-details/event-details.component';
import { IPaymentMethod } from '../../models/IPaymentMethod';
import { tap } from 'rxjs';
import { IOrganization } from '../../models/IOrganization';
import { IPerson } from '../../models/IPerson';
import { CommonModule } from '@angular/common';
import { TitleBannerComponent } from '../title-banner/title-banner.component';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-participant-details',
  standalone: true,
  imports: [CommonModule, TitleBannerComponent, FormsModule, RouterModule],
  templateUrl: './participant-details.component.html',
  styleUrl: './participant-details.component.scss',
})
export class ParticipantDetailsComponent implements OnInit {
  participantId?: string;
  participant?: Participant;
  paymentMethods: IPaymentMethod[] = [];

  constructor(
    private router: Router,
    private personService: PersonService,
    private organizationService: OrganizationService,
    private paymentMethodService: PaymentMethodService
  ) {}

  ngOnInit(): void {
    this.participantId =
      this.router.url.split('/').pop()?.replace('?isOrganization=true', '') ||
      '';
    const isOrganization = this.router.url.includes('isOrganization=true');

    this.paymentMethodService.getAll().subscribe((paymentMethods) => {
      this.paymentMethods = paymentMethods;
    });

    if (isOrganization) {
      this.organizationService
        .get(this.participantId)
        .subscribe((organization) => {
          if (organization) {
            this.participant = {
              id: this.participantId,
              isOrganization: true,
              firstName: organization.name,
              lastName: '',
              personalCode: organization.registrationNumber,
              paymentMethodId: organization.paymentMethodId,
              numberOfParticipants: organization.numberOfParticipants,
              description: organization.description || '',
              eventId: organization.eventId,
            };
          }
        });
    } else {
      this.personService.get(this.participantId).subscribe((person) => {
        if (person) {
          this.participant = {
            id: this.participantId,
            isOrganization: false,
            firstName: person.firstName,
            lastName: person.lastName,
            personalCode: person.personalCode,
            paymentMethodId: person.paymentMethodId,
            numberOfParticipants: 1,
            description: person.description || '',
            eventId: person.eventId,
          };
        }
      });
    }
  }

  onSubmit(): void {
    if (!this.participant) return;

    this.participant.isOrganization
      ? this.editOrganization()
      : this.editPerson();
  }

  private editPerson() {
    const person: IPerson = {
      id: this.participantId,
      firstName: this.participant!.firstName,
      lastName: this.participant!.lastName,
      personalCode: this.participant!.personalCode,
      eventId: this.participant!.eventId!,
      paymentMethodId: this.participant!.paymentMethodId,
      description: this.participant!.description,
    };

    this.personService
      .put(person, person.id!)
      .pipe(
        tap((response: any) => {
          if (!response)
            this.router.navigate(['/yritused', this.participant!.eventId]);
        })
      )
      .subscribe();
  }

  private editOrganization() {
    const organization: IOrganization = {
      id: this.participantId,
      name: this.participant!.firstName + ' ' + this.participant!.lastName,
      description: this.participant!.description,
      registrationNumber: this.participant!.personalCode,
      numberOfParticipants: this.participant!.numberOfParticipants,
      eventId: this.participant!.eventId!,
      paymentMethodId: this.participant!.paymentMethodId,
    };

    this.organizationService
      .put(organization, organization.id!)
      .pipe(
        tap((response: any) => {
          if (!response)
            this.router.navigate(['/yritused', this.participant!.eventId]);
        })
      )
      .subscribe();
  }
}

<div class="form-page-container">
  <app-title-banner [title]="'Osavõtja info'"></app-title-banner>
  <div class="form-container">
    <div class="title">Osavõtja info</div>
    <div class="form" *ngIf="!!participant">
      <div class="form-group">
        <label for="name"
          >{{ participant.isOrganization ? "Nimi" : "Eesnimi" }}:</label
        >
        <input type="text" id="name" [(ngModel)]="participant.firstName" />
      </div>

      <div class="form-group" *ngIf="!participant?.isOrganization">
        <label for="last-name">Perenimi:</label>
        <input type="text" id="last-name" [(ngModel)]="participant.lastName" />
      </div>

      <div class="form-group">
        <label for="code"
          >{{ participant.isOrganization ? "Reg nr" : "Isikukood" }}:</label
        >
        <input type="text" id="code" [(ngModel)]="participant.personalCode" />
      </div>

      <div class="form-group" *ngIf="participant.isOrganization">
        <label for="numberOfParticipants">Tulevate osavõtjate arv:</label>
        <input
          type="number"
          id="numberOfParticipants"
          [(ngModel)]="participant.numberOfParticipants"
        />
      </div>

      <div class="form-group">
        <label for="paymentMethod">Makseviis:</label>
        <select
          id="paymentMethod"
          class="input"
          [(ngModel)]="participant.paymentMethodId"
        >
          <option
            *ngFor="let paymentMethod of paymentMethods"
            value="{{ paymentMethod.id }}"
          >
            {{ paymentMethod.name }}
          </option>
        </select>
      </div>

      <div class="form-group">
        <label for="description">Lisainfo:</label>
        <textarea
          id="description"
          class="input"
          [(ngModel)]="participant.description"
        ></textarea>
      </div>
    </div>

    <div class="buttons">
      <button
        class="button secondary"
        [routerLink]="['/yritused', participant?.eventId]"
      >
        Tagasi
      </button>
      <button class="button primary" (click)="onSubmit()">Salvesta</button>
    </div>
  </div>
</div>

// client-react/src/components/participant-details/ParticipantDetails.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import TitleBanner from '../title-banner/TitleBanner';
import PersonService from '../../services/PersonService';
import { IParticipant } from '../../models/IParticipant';
import OrganizationService from '../../services/OrganizationService';
import { IPaymentMethod } from '../../models/IPaymentMethod';
import PaymentMethodService from '../../services/PaymentMethodService';
import { IPerson } from '../../models/IPerson';

const ParticipantDetails = () => {
    const { id } = useParams();

    const isOrganization = window.location.href.includes("isOrganization=true");

    const [participant, setParticipant] = useState<IParticipant | null>(null);
    const [paymentMethods, setPaymentMethods] = useState<IPaymentMethod[]>([]);

    useEffect(() => {
        loadParticipant();
    });

    useEffect(() => {
        loadPaymentMethods();
    }, []);

    const navigate = useNavigate();

    const loadParticipant = () => {
        if (isOrganization) {
            OrganizationService
                .get(id!)
                .then((organization) => {
                    if (organization.data) {
                        setParticipant({
                            id: id,
                            isOrganization: true,
                            firstName: organization.data.name,
                            lastName: "",
                            personalCode: organization.data.registrationNumber,
                            paymentMethodId: organization.data.paymentMethodId,
                            numberOfParticipants: organization.data.numberOfParticipants,
                            description: organization.data.description || "",
                            eventId: organization.data.eventId,
                        });
                    }
                });
        } else {
            PersonService.get(id!).then((person) => {
                if (person.data) {
                    setParticipant({
                        id: id,
                        isOrganization: false,
                        firstName: person.data.firstName,
                        lastName: person.data.lastName,
                        personalCode: person.data.personalCode,
                        paymentMethodId: person.data.paymentMethodId,
                        numberOfParticipants: 1,
                        description: person.data.description || "",
                        eventId: person.data.eventId,
                    });
                }
            });
        }
    };

    const loadPaymentMethods = () => {
        PaymentMethodService.getAll().then(paymentMethods => {
            setPaymentMethods(paymentMethods.data);
        });
    };

    const onSubmit = (): void => {
        if (!participant) return;

        participant.isOrganization
            ? editOrganization()
            : editPerson();
    };

    const editPerson = () => {
        const person: IPerson = {
            id: id,
            firstName: participant!.firstName,
            lastName: participant!.lastName,
            personalCode: participant!.personalCode,
            eventId: participant!.eventId!,
            paymentMethodId: participant!.paymentMethodId,
            description: participant!.description,
        };

        PersonService.put(person, person.id!)
            .then(person => {
                navigate(`/events/${person.data.eventId}`);
            });
    };

    const editOrganization = () => {
        const organization = {
            id: id,
            name: participant!.firstName,
            description: participant!.description,
            registrationNumber: participant!.personalCode,
            numberOfParticipants: participant!.numberOfParticipants,
            eventId: participant!.eventId!,
            paymentMethodId: participant!.paymentMethodId,
        };

        OrganizationService.put(organization, organization.id!)
            .then(organization => {
                window.open(`/events/${organization.data.eventId}`, "_self");
            });
    };

    if (!participant) {
        navigate("/");
        return null;
    }

    return (
        <div className="form-page-container">
            <TitleBanner title="Participant Details" />
            <div className="form-container">
                <div className="title">Participant Details</div>
                <div className="form">
                    <div className="form-group">
                        <label htmlFor="name">{participant.isOrganization ? "Name" : "First Name"}:</label>
                        <input type="text" id="name" value={participant.firstName} onChange={e => setParticipant({ ...participant, firstName: e.target.value })} />
                    </div>

                    {!participant.isOrganization && (
                        <div className="form-group">
                            <label htmlFor="last-name">Last Name:</label>
                            <input type="text" id="last-name" value={participant.lastName} onChange={e => setParticipant({ ...participant, lastName: e.target.value })} />
                        </div>
                    )}

                    <div className="form-group">
                        <label htmlFor="code">
                            {participant.isOrganization ? "Reg nr" : "Personal Code"}:
                        </label>
                        <input
                            type="text"
                            id="code"
                            value={participant.personalCode}
                            onChange={e =>
                                setParticipant({ ...participant, personalCode: e.target.value })
                            }
                        />
                    </div>

                    {participant.isOrganization && (
                        <div className="form-group">
                            <label htmlFor="numberOfParticipants">Number of comming participants:</label>
                            <input
                                type="number"
                                id="numberOfParticipants"
                                value={participant.numberOfParticipants}
                                onChange={e => setParticipant({ ...participant, numberOfParticipants: parseInt(e.target.value) })}
                            />
                        </div>
                    )}

                    <div className="form-group">
                        <label htmlFor="paymentMethod">Payment Method:</label>
                        <select
                            id="paymentMethod"
                            className="input"
                            value={participant.paymentMethodId}
                            onChange={e => setParticipant({ ...participant, paymentMethodId: e.target.value })}
                        >
                            {paymentMethods.map(paymentMethod => (
                                <option key={paymentMethod.id} value={paymentMethod.id}>
                                    {paymentMethod.name}
                                </option>
                            ))}
                        </select>
                    </div>

                    <div className="form-group">
                        <label htmlFor="description">Description:</label>
                        <textarea
                            id="description"
                            className="input"
                            value={participant.description}
                            onChange={e => setParticipant({ ...participant, description: e.target.value })}
                        />
                    </div>
                </div>
                <div className="buttons">
                    <button
                        className="button secondary"
                        onClick={() => navigate(`/events/${participant?.eventId}`)}
                    >
                        Back
                    </button>
                    <button className="button primary" onClick={onSubmit}>Save</button>
                </div>
            </div>
        </div>
    );
};

export default ParticipantDetails;
